### Get all existing parties
GET http://167.71.70.141/parties

### Get party at id = 1
GET http://167.71.70.141/parties/1

### Create new party (id can be set to null, or anything - it's set automatically)
POST http://167.71.70.141/parties
Content-Type: application/json

{
    "id": 666,
    "host_id": 2,
    "title": "Hiroshima Rave",
    "description": "WTF is a KILOMETER! RAHHHHHHH",
    "latitude": 0.0,
    "longitude": 0.0,
    "capacity": 1000,
    "attendees": 1,
    "start_time": 0,
    "visibility": 1
  }

### Update existing party at id = 2
PUT http://127.0.0.1:8000/parties/2
Content-Type: application/json

{
    "id": 666,
    "host_id": 2,
    "title": "Big Hiroshima Firework Show",
    "description": "WTF is a kilometer! RAAAAAAAAHHHHHHHHHHH!",
    "latitude": 0.0,
    "longitude": 0.0,
    "capacity": 100,
    "attendees": 900,
    "start_time": 0,
    "visibility": 1
  }


### Get attendees of party at id = 2
GET http://167.71.70.141/parties/2/users